/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikestation;

//
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Villosa
 */
public class StationWindow extends javax.swing.JFrame {
    
    private Connection con;
    //Connection conn = DriverManager.getConnection("jdbc:derby://localhost/test;create=true;user=APP;pass=APP");
    private Statement stmt ;
    private Object timer;
    private int table1Row=20;
    DefaultTableModel model;
    BikeData adminData = new BikeData();
    /**
     * Creates new form StationWindow
     */
    public StationWindow() throws SQLException {
        
        initComponents();
        con = DriverManager.getConnection("jdbc:mysql://localhost/bicyclesystem","root","12345"); //localhost database XAMPP
     //   con = DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net/sql6116222","sql6116222","x1Cu8IqzkX");
      //   con = DriverManager.getConnection("jdbc:mysql://50.87.147.177:3306/abel_interiordesigns","abel_um123","Um123!"); //online database 
          
        ////
        //Jtable1 
        //getNumberRows();
        model = new DefaultTableModel(new String[] {"BikeName","Station_Rented","Status","User_ID","Time_Rented"},0);
        jTable1.setModel(model);
        model.setNumRows(table1Row);
        model.setRowCount(table1Row);
        
        getBicycleUpdate();
        System.out.println("Connection OK!");
       // con.close();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bikeComboBox = new javax.swing.JComboBox();
        stationComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        userField2 = new javax.swing.JTextField();
        addButton2 = new javax.swing.JButton();
        statusComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bicycle", "Station", "Status", "User", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 202, 135));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("STATION STATUS - DEMO");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Add Entry");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Bicycle");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Station");

        bikeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bicycle1", "Bicycle2", "Bicycle3", "Bicycle4", "Bicycle5", " " }));

        stationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Station1", "Station2", "Station3" }));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("User");

        addButton2.setText("ADD ENTRY");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        statusComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rent", "Return", "Reserve", "Repair" }));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Action");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bikeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bikeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(userField2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
        String bike,station,status,user,time;
        int bikeid;

        bike = (String) bikeComboBox.getSelectedItem();
        station = (String) stationComboBox.getSelectedItem();
        status = (String) statusComboBox1.getSelectedItem();
        user = userField2.getText();

        Date mydate = new Date();

        String newdate = new SimpleDateFormat("MMM dd yyyy HH:mm:ss").format(mydate);
        CallableStatement cs = null;
        
        // IF THE ACTION IS RENT
        if(status.contentEquals("Rent")){             
            String sqlstmt = "INSERT INTO all_entries "
                + "values(0,'"+bike+"','"+station+"','"+newdate+"','Rented',"+user+",1)"; //SQL Statement
            //try and catch error
            try {
                cs = con.prepareCall(sqlstmt);
            } catch (SQLException ex) {
                Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Rent bike successful");
            JOptionPane.showMessageDialog(bikeComboBox, "Rent bike successful");
            
        // IF THE ACTION IS RESERVATION    
        }else if(status.contentEquals("Reserve")){     
            String sqlstmt = "INSERT INTO all_entries "
                + "values(0,'"+bike+"','"+station+"','"+newdate+"','Reserve',"+user+",1)"; //SQL Statement
            //try and catch error
            try {
                cs = con.prepareCall(sqlstmt);
            }catch (SQLException ex) {
                Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("Reserved bike successful");
            JOptionPane.showMessageDialog(bikeComboBox, "Reserved bike successful");
        // IF THE ACTION IS RETURN    
        }else if(status.contentEquals("Repair")){     
            String sqlstmt = "INSERT INTO all_entries "
                + "values(0,'"+bike+"','"+station+"','"+newdate+"','Repair',"+user+",1)"; //SQL Statement
            //try and catch error
            try {
                cs = con.prepareCall(sqlstmt);
            }catch (SQLException ex) {
                Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("Reserved bike successful");
            JOptionPane.showMessageDialog(bikeComboBox, "Repair bike successful");
        // IF THE ACTION IS RETURN    
        }else{     
            String sqlstmt = "INSERT INTO all_entries "
                + "values(0,'"+bike+"','"+station+"','"+newdate+"','Returned',"+user+",1)"; //SQL Statement
                //try and catch error 
            JOptionPane.showMessageDialog(bikeComboBox, "Return bike successful");
            System.out.println("Return bike successful");
            try {
                cs = con.prepareCall(sqlstmt);
            } catch (SQLException ex) {
                Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }

        try {
            cs.execute(); //execute the sql command
        } catch (SQLException ex) {
            Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cs.close();
        } catch (SQLException ex) {
            Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButton2ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            sentBicycleUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        getBicycleUpdate();

        Date mydate = new Date();
        System.out.println("System is updated at " + mydate.toString());
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new StationWindow().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(StationWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }
    
    
    public void getBicycleUpdate(){
        int c=0,r=0;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException cnfe) {
            System.err.println("mySQL driver not found.");
        }
        try {
            stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM bike_status");
              
            while (rs.next()){
                int bikeId = rs.getInt("BikeID");
                String bikeName = rs.getString("BikeName");
                String station = rs.getString("Station_Rented");
                String status = rs.getString("Status");
                int user = rs.getInt("User_ID");
                String time = rs.getString("Time_Rented");
                int duration = rs.getInt("Duration");

                c=0;    //reset column
                

                jTable1.setValueAt(bikeName, r, c);
                c++;
                jTable1.setValueAt(station, r, c);
                c++;
                jTable1.setValueAt(status, r, c);
                c++;
                jTable1.setValueAt(user, r, c);
                c++;
                jTable1.setValueAt(time, r, c);
                c++;
                r++;
            }
        } catch (SQLException ex) {
        }
    }
    
    
    public void sentBicycleUpdate() throws SQLException{
        int c=0,r=0;
        int bikeId =32154,duration=0,user=0;
        String bikeName="none",station="none",status="none",time ="none";
        String temp;
                
        Object temp2;
        ResultSet rs = stmt.executeQuery("SELECT * FROM bike_status");
        
        while (rs.next()){
            c= 0;
            bikeId = rs.getInt("BikeID");
                //get values 
            bikeName = (String) jTable1.getValueAt( r, c);
            c++;
            station = (String) jTable1.getValueAt( r, c);
            c++;
            status = (String) jTable1.getValueAt( r, c);
            c++;
            temp2  =  jTable1.getValueAt( r, c);
            c++;
            time = (String) jTable1.getValueAt( r, c);
            c++;
            r++;    
            
            System.out.println(bikeId + " " + bikeName + " " + station + " "
                   + status + " " + user + " " + time+ " " + duration + " - " );
                    
            CallableStatement cs = null;
            
            try {
                stmt = con.createStatement();
                String sqlstmt =  "UPDATE bike_status SET "
                        + "BikeName = '"+bikeName+"',Station_Rented = '"+station+"',Status = '"+status+"',"
                        + "User_ID = "+temp2+",Time_Rented = '"+time+"' WHERE `bike_status`.`BikeID` = "+bikeId+";";   
                
                    cs = con.prepareCall(sqlstmt); 
                    cs.execute(); //execute the sql command 
                            
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
        
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton2;
    private javax.swing.JComboBox bikeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox stationComboBox;
    private javax.swing.JComboBox statusComboBox1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userField2;
    // End of variables declaration//GEN-END:variables
}
